version: "3.9"

services:
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:8000"